// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('AllNews', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('AllNews', async function() {
    await driver.get("https://newsxpress-7bjk.onrender.com/all")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".transition-colors:nth-child(1)")).click()
    await driver.findElement(By.css(".close-btn")).click()
    await driver.findElement(By.css(".Toastify__close-button path")).click()
    await driver.findElement(By.css(".pr-10")).click()
    await driver.findElement(By.css(".close-btn")).click()
    await driver.findElement(By.css(".hidden > .lucide")).click()
    await driver.findElement(By.css(".hidden > .overflow-y-auto .text-sm:nth-child(2)")).click()
    await driver.findElement(By.css(".close-btn")).click()
    await driver.findElement(By.css(".hidden > .overflow-y-auto .w-full")).click()
    await driver.findElement(By.css(".close-btn")).click()
    await driver.findElement(By.css(".hidden > .lucide > circle")).click()
    await driver.findElement(By.css(".hidden .p-2 path:nth-child(1)")).click()
    await driver.findElement(By.css(".pr-10")).click()
    await driver.findElement(By.css(".close-btn")).click()
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".relative:nth-child(1) > .inset-0")).click()
    await driver.findElement(By.css(".absolute > .lucide")).click()
    await driver.findElement(By.css(".h-10")).click()
  })
})
