// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Bookmarks', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Bookmarks', async function() {
    await driver.get("https://newsxpress-7bjk.onrender.com/all")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".hidden > .lucide")).click()
    await driver.findElement(By.css(".hidden > .lucide")).click()
    await driver.findElement(By.css(".relative:nth-child(1) > .inset-0")).click()
    await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .flex:nth-child(1) > .lucide")).click()
    {
      const element = await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .flex:nth-child(1) > .lucide"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".focus\\3A border-red-500")).sendKeys("Important to know.")
    await driver.findElement(By.css(".bg-black\\/60")).click()
    await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .flex:nth-child(1) > .lucide")).click()
    {
      const element = await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .flex:nth-child(1) > .lucide"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".focus\\3A border-red-500")).click()
    await driver.findElement(By.css(".focus\\3A border-red-500")).sendKeys("Great insight")
    await driver.findElement(By.css(".hover\\3A bg-gray-700")).click()
    await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .flex:nth-child(1) > .lucide")).click()
    {
      const element = await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .flex:nth-child(1) > .lucide"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute > .mt-4 > .flex > .flex:nth-child(1)")).click()
    await driver.findElement(By.css(".focus\\3A border-red-500")).sendKeys("great news")
    await driver.findElement(By.css(".py-2:nth-child(2)")).click()
    await driver.findElement(By.css(".lg\\3Ainline-flex")).click()
    await driver.findElement(By.css(".hidden .w-full:nth-child(1) > span")).click()
    await driver.findElement(By.css(".mt-3 > .w-full")).click()
    await driver.findElement(By.css(".mt-3 > .w-full")).sendKeys("i love this article")
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.linkText("Read")).click()
    vars["win7588"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win7588"])
    {
      const element = await driver.findElement(By.linkText("Latest"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.close()
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.css(".mt-3 > .w-full")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".h-44")).click()
    vars["win7430"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win7430"])
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.css(".py-2:nth-child(2)")).click()
    await driver.findElement(By.css(".Toastify__close-button path")).click()
    await driver.findElement(By.css(".lg\\3Ainline-flex")).click()
    await driver.findElement(By.css(".hidden .space-y-2 > .w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".gap-2:nth-child(1) > span:nth-child(2)")).click()
  })
})
