// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CategoryNews', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CategoryNews', async function() {
    await driver.get("https://newsxpress-7bjk.onrender.com/all")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".px-3:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css(".border-transparent"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".gap-2:nth-child(3)")).click()
    await driver.findElement(By.css(".flex:nth-child(4) > span")).click()
    {
      const element = await driver.findElement(By.css(".lucide-trophy > path:nth-child(3)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".flex:nth-child(5) > span")).click()
    {
      const element = await driver.findElement(By.css(".flex:nth-child(6) > span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".flex:nth-child(6) > span")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".flex:nth-child(7) > span")).click()
    await driver.findElement(By.css(".flex:nth-child(8) > span")).click()
    await driver.findElement(By.css(".flex:nth-child(9) > span")).click()
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".lucide-shield")).click()
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
  })
})
