// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('HelpSupport', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('HelpSupport', async function() {
    await driver.get("https://newsxpress-7bjk.onrender.com/all")
    await driver.manage().window().setRect({ width: 1536, height: 816 })
    await driver.findElement(By.css(".hidden > .lucide")).click()
    await driver.findElement(By.css(".hidden .space-y-2 > .w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".hidden > .lucide > circle")).click()
    await driver.findElement(By.css(".hidden .flex > .text-sm:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css(".hidden .flex > .text-sm:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".hidden .bg-gray-50 > div > .w-full")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".mb-6")).click()
    await driver.findElement(By.name("message")).click()
    await driver.findElement(By.name("message")).click()
    await driver.findElement(By.name("message")).click()
    await driver.findElement(By.name("message")).click()
    await driver.findElement(By.name("message")).sendKeys("I am unable to accees my personlized feed")
    await driver.findElement(By.css(".disabled\\3Aopacity-60")).click()
    await driver.findElement(By.css(".Toastify__close-button > svg")).click()
  })
})
