// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('NewsCard', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('NewsCard', async function() {
    await driver.get("https://newsxpress-7bjk.onrender.com/all")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".hidden > .lucide")).click()
    await driver.findElement(By.css(".hidden > .lucide")).click()
    await driver.findElement(By.css(".relative:nth-child(2) > .inset-0")).click()
    await driver.findElement(By.css(".h-full:nth-child(2) > .relative .flex:nth-child(1) path")).click()
    {
      const element = await driver.findElement(By.css(".h-full:nth-child(2) > .relative .flex:nth-child(1) path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".hover\\3Atext-red-400")).click()
    await driver.findElement(By.css(".h-full:nth-child(2) > .relative .flex:nth-child(2) > .lucide")).click()
    {
      const element = await driver.findElement(By.css(".h-full:nth-child(2) > .relative .flex:nth-child(2) > .lucide"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".p-4 > .px-3")).click()
    await driver.findElement(By.css(".p-4 > .px-3")).click()
    {
      const element = await driver.findElement(By.css(".flex-grow"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".flex-grow"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".flex-grow"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".p-4 > .px-3")).click()
    await driver.findElement(By.css(".p-4 > .px-3")).sendKeys("hin")
    await driver.findElement(By.css(".py-1:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".h-full:nth-child(2) > .relative .p-2\\.5:nth-child(3) > .lucide")).click()
    await driver.findElement(By.linkText("Read More")).click()
    await driver.findElement(By.linkText("Read More")).click()
  })
})
