// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Profile&Support', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Profile&Support', async function() {
    await driver.get("https://newsxpress-7bjk.onrender.com/all")
    await driver.manage().window().setRect({ width: 1536, height: 816 })
    await driver.findElement(By.css(".h-10")).click()
    await driver.findElement(By.css(".hidden .flex > .text-sm:nth-child(2)")).click()
    await driver.findElement(By.css(".hidden .bg-gray-50 > div:nth-child(1) .text-xs")).click()
    {
      const element = await driver.findElement(By.css(".hidden .bg-gray-50 > div:nth-child(1) .text-xs"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".hidden > .overflow-y-auto .px-3:nth-child(2)")).click()
    await driver.findElement(By.css(".hidden .bg-gray-50 > div:nth-child(2) .text-xs")).click()
    {
      const element = await driver.findElement(By.css(".hidden .bg-gray-50 > div:nth-child(2) .text-xs"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".hidden > .overflow-y-auto .px-3:nth-child(2)")).click()
    await driver.findElement(By.css(".Toastify__close-button > svg")).click()
    await driver.findElement(By.css(".hidden > .overflow-y-auto .relative")).click()
    await driver.findElement(By.css(".hidden > .overflow-y-auto .relative")).click()
    {
      const element = await driver.findElement(By.css(".hidden > .overflow-y-auto .relative"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".Toastify__close-button path")).click()
    await driver.findElement(By.css(".hidden .p-2 > .lucide")).click()
  })
})
