// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SearchBar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SearchBar', async function() {
    await driver.get("https://newsxpress-7bjk.onrender.com/all")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    {
      const element = await driver.findElement(By.css(".lucide-film"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".hidden > .lucide")).click()
    await driver.findElement(By.css(".hidden > .lucide")).click()
    await driver.findElement(By.css(".pr-10")).click()
    await driver.findElement(By.css(".pr-10")).sendKeys("PM Modi")
    await driver.findElement(By.css(".pr-10")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".relative:nth-child(1) > .inset-0")).click()
    await driver.findElement(By.css(".absolute > .lucide")).click()
    await driver.findElement(By.css(".pr-10")).click()
    await driver.findElement(By.css(".pr-10")).click()
    await driver.findElement(By.css(".pr-10")).click()
    {
      const element = await driver.findElement(By.css(".pr-10"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
  })
})
