const { baseTemplate } = require("../../auth/email/templates/baseTemplate");
const { colors, styles } = require("../../config/email/sharedStyles");
const { sectionLabel, title, subtitle } = require("../../config/email/components");

const adminNotificationContent = ({ name, email, message }) => `
  <!-- Section Label -->
  ${sectionLabel("Support Request")}

  <!-- Title -->
  ${title(`New Contact Message From ${name}`)}

  <!-- Intro -->
  ${subtitle("You have received a new help & support inquiry from a user.")}

  <!-- Sender Info -->
  <div style="${styles.alertBox}; margin-top:22px;">
    <p style="margin:0 0 8px;"><strong>👤 Name:</strong> ${name}</p>
    <p style="margin:0;"><strong>📧 Email:</strong> ${email}</p>
  </div>

  <!-- Message Box -->
  <div style="${styles.box}; margin-top:22px;">
    <p style="margin:0 0 12px; font-weight:600; color:${colors.text};">📝 User Message:</p>
    <p style="${styles.text}; margin:0;">${message}</p>
  </div>

  <!-- Footer Note -->
  <p style="
    text-align:center;
    margin-top:28px;
    font-size:12px;
    color:${colors.muted};
  ">
    This message was automatically generated by NewsXpress Support System.
  </p>
`;

const adminNotificationTemplate = (data) => baseTemplate(adminNotificationContent(data));

module.exports = { adminNotificationTemplate };
